name: CI

on:
  push:
    branches: [ "main", "auth" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore TelemetryWerk.Api/TelemetryWerk.Api.slnx
    
    - name: Build
      run: dotnet build TelemetryWerk.Api/TelemetryWerk.Api.slnx -c Release --no-restore
    
    - name: Test
      run: dotnet test TelemetryWerk.Api/TelemetryWerk.Api.slnx -c Release --no-build --verbosity normal
      
    - name: Publish API (Windows EXE)
      run: dotnet publish TelemetryWerk.Api/TelemetryWerk.Api.Host/TelemetryWerk.Api.Host.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/api-win
      
    - name: Remove Development Config
      run: rm -f ./publish/api-win/appsettings.Development.json
      
    - name: Upload API Artifact
      uses: actions/upload-artifact@v4
      with:
        name: telemetry-api-windows-exe
        path: ./publish/api-win

  build-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore TelemetryWerk.Ui/TelemetryWerk.Ui.slnx
      
    - name: Build
      run: dotnet build TelemetryWerk.Ui/TelemetryWerk.Ui.slnx -c Release --no-restore
      
    - name: Publish UI (Windows EXE)
      run: dotnet publish TelemetryWerk.Ui/TelemetryWerk.Ui/TelemetryWerk.Ui.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/ui-win
      
    - name: Remove Development Config
      run: rm -f ./publish/ui-win/appsettings.Development.json
      
    - name: Upload UI Artifact
      uses: actions/upload-artifact@v4
      with:
        name: telemetry-ui-windows-exe
        path: ./publish/ui-win
